apiVersion: apps/v1
kind: Deployment
metadata:
  name: haproxy-sidecar
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          image: haproxy:2.7
          ports:
            - containerPort: 8000
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 128Mi

        - name: haproxy
          image: kayaman/haproxy
          tag: '2.0'
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 300m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi

        - name: spoe-agent
          image: kayaman/spoe-agent
          imagePullPolicy: Always
          tag: latest
          # command: ['python', '/app/agent.py']
          ports:
            - containerPort: 9000
          # volumeMounts:
          #   - name: spoe-agent-config
          #     mountPath: /app/agent.py
          #     subPath: agent.py
          #   - name: spoe-agent-config
          #     mountPath: /app/agent.conf
          #     subPath: agent.conf
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
          env:
            - name: DOWNSTREAM_URL
              value: 'http://http-event-processor:8080/http-events'

      volumes:
        - name: haproxy-config
          configMap:
            name: haproxy-config
        - name: spoe-agent-config
          configMap:
            name: spoe-agent-config
