application:
  name: myapp
  image:
    repository: kayaman/demo-app
    tag: latest
    pullPolicy: Always
  port: 8000
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi

haproxy:
  image:
    repository: haproxy
    tag: '2.7'
    pullPolicy: IfNotPresent
  port: 8080
  resources:
    limits:
      cpu: 300m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
  spoe:
    enabled: true
    bufferSize: 16384
    timeout:
      hello: 3s
      idle: 10s
      processing: 10s

spoeAgent:
  enabled: true
  image:
    repository: kayaman/spoe-agent
    tag: latest
    pullPolicy: Always
  port: 9000
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
  downstream:
    url: 'http://http-event-processor:8080/http-events'
    timeoutSeconds: 5

service:
  type: NodePort
  port: 80
